import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro', // This references docs/intro.md
    {
      type: 'category',
      label: 'Introduction to Physical AI',
      items: [{type: 'autogenerated', dirName: 'introduction'}],
    },
    {
      type: 'category',
      label: 'Module 1 - The Robotic Nervous System (ROS 2)',
      items: [{type: 'autogenerated', dirName: 'module-1-ros2'}],
    },
    {
      type: 'category',
      label: 'Module 2 - The Digital Twin (Gazebo & Unity)',
      items: [{type: 'autogenerated', dirName: 'module-2-digital-twin'}],
    },
    {
      type: 'category',
      label: 'Module 3 - The AI-Robot Brain (NVIDIA Isaac)',
      items: [{type: 'autogenerated', dirName: 'module-3-isaac'}],
    },
    {
      type: 'category',
      label: 'Module 4 - Vision-Language-Action (VLA)',
      items: [{type: 'autogenerated', dirName: 'module-4-vla'}],
    },
    {
      type: 'category',
      label: 'Weekly Breakdown Chapters',
      items: [{type: 'autogenerated', dirName: 'weekly-breakdowns'}],
    },
    {
      type: 'category',
      label: 'Assessment Chapters',
      items: [{type: 'autogenerated', dirName: 'assessments'}],
    },
    {
      type: 'category',
      label: 'Hardware Chapters',
      items: [{type: 'autogenerated', dirName: 'hardware'}],
    },
    {
      type: 'category',
      label: 'Cloud vs On-Premise Lab Setup',
      items: [{type: 'autogenerated', dirName: 'lab-setup'}],
    },
  ],
};

export default sidebars;